services:
  research:
    image: csr/base
    hostname: <hostname to use>
    ports:
      - "<port number>:22"
    volumes:
      - /data/kenpu/dbresearch/home:/home
      - /dataset/kenpu/dbresearch:/data
      - ./users:/etc/users
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: <an integer which is the number of gpus>
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=<comma separated GPU ids>